# Generated by Django 3.1.1 on 2020-09-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20200914_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comauthor', models.CharField(max_length=50, verbose_name='name')),
                ('comcontent', models.CharField(max_length=50, verbose_name='content')),
                ('comdate', models.DateTimeField(auto_now_add=True)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='timeline.timeline', verbose_name='Timeline')),
            ],
        ),
    ]
