# Generated by Django 3.1.1 on 2020-09-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comdate']},
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['-date']},
        ),
    ]
